### ISSUE TITLE
Next.js App or Pages Router 

### ISSUE THREAD

**Issue by benjamin-shuster** [hariDasu/is322-next-app#12]
Next.js has 2 routers, the old pages router and the new app router. We need to decide which to use for the project. 

[App Router Docs](https://nextjs.org/docs/app)
[Pages Router Docs](https://nextjs.org/docs/pages)

**Comment by hariDasu** [comment]
app router wins

**Comment by hariDasu** [comment]
https://dev.to/remusris/t3-stack-template-supabase-w-auth-db-and-shadcn-ui-basic-setup-2bl9
