### ISSUE TITLE
Figma integration

### ISSUE THREAD

**Issue by hariDasu** [hariDasu/is322-next-app#9]
https://github.com/orgs/NJIT-IS332-Fall2023/projects/2/views/1?pane=issue&itemId=42269263

need some way to easily link designs to feature / bug tickets so developers don't have to dig through all the designs to find the relevant issue

**Comment by benjamin-shuster** [comment]
After a bit of googling, I think the best (and maybe only) way to do this is to include the link to Figma (to the frame or component) at the end of the GH issue 
to get the link, open the context menu>Copy/Paste as > Copy link
![image](https://github.com/NJIT-IS332-Fall2023/is322-next-app/assets/77933963/5b8e96e0-19b4-4224-9c98-664968335bd0)


ex: 
[Google Auth Figma](https://www.figma.com/file/oL4OC1GAgUpaSE0TPqlifl/MARVEL-APP-(Community)?type=design&node-id=0-496&mode=design&t=377lDIuoQ0sp7HBL-4)  
[Sign In Page](https://www.figma.com/file/oL4OC1GAgUpaSE0TPqlifl/MARVEL-APP-(Community)?type=design&node-id=0-484&mode=design&t=377lDIuoQ0sp7HBL-4)

clicking on these links take you to the component on the Figma document
